//
// This file generated by rdl 1.5.0
//

package globalip

import (
	"encoding/json"
	"fmt"
	rdl "github.com/ardielle/ardielle-go/rdl"
)

var _ = rdl.Version
var _ = json.Marshal
var _ = fmt.Printf

//
// Octet -
//
type Octet string

//
// IPAddress -
//
type IPAddress string

//
// Response -
//
type Response struct {
	Origin IPAddress `json:"origin"`
}

//
// NewResponse - creates an initialized Response instance, returns a pointer to it
//
func NewResponse(init ...*Response) *Response {
	var o *Response
	if len(init) == 1 {
		o = init[0]
	} else {
		o = new(Response)
	}
	return o
}

type rawResponse Response

//
// UnmarshalJSON is defined for proper JSON decoding of a Response
//
func (self *Response) UnmarshalJSON(b []byte) error {
	var m rawResponse
	err := json.Unmarshal(b, &m)
	if err == nil {
		o := Response(m)
		*self = o
		err = self.Validate()
	}
	return err
}

//
// Validate - checks for missing required fields, etc
//
func (self *Response) Validate() error {
	if self.Origin == "" {
		return fmt.Errorf("Response.origin is missing but is a required field")
	} else {
		val := rdl.Validate(GlobalIPSchema(), "IPAddress", self.Origin)
		if !val.Valid {
			return fmt.Errorf("Response.origin does not contain a valid IPAddress (%v)", val.Error)
		}
	}
	return nil
}
